import React from "react";
import styled from "@emotion/styled";
/**
 * `<WorldHexagonMap>` ('World hexagon map')
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <WorldHexagonMap/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/6903412f-e22d-423a-90a0-ce549ab20710)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : unknown://undefined/625:18486 -->
 */
export function HEXOGON() {
  return (
    <RootWrapperWorldHexagonMap>
      <WidgetLSizeTimelineChart>
        <Info>
          <Value>
            <Value_0001>
              <Title>Sales Figures</Title>
              <Value_0002>$10,430</Value_0002>
            </Value_0001>
          </Value>
        </Info>
        <Graph>
          <Chart>
            <Column />
            <Column_0001 />
            <Column_0002 />
            <Column_0003 />
            <Column_0004 />
            <Column_0005 />
            <Column_0004 />
            <Column_0007 />
            <Column_0008 />
            <Column_0008 />
            <Column_0003 />
            <Column_0003 />
            <Column_0007 />
            <Column_0003 />
            <Column_0014 />
            <Column_0015 />
            <Column_0016 />
            <Column_0017 />
            <Column_0015 />
            <Column_0019 />
            <Column_0020 />
            <Column_0021 />
            <Column_0022 />
            <Column_0023 />
            <Column_0024 />
            <Column_0025 />
            <Column_0019 />
            <Column_0027 />
            <Column_0027 />
            <Column_0029 />
            <Column_0027 />
            <Column_0017 />
            <Column_0032 />
            <Column_0015 />
            <Column_0015 />
            <Column_0017 />
            <Column_0015 />
            <Column_0014 />
            <Column_0015 />
            <Column_0016 />
            <Column_0017 />
            <Column_0015 />
            <Column_0015 />
            <Column_0043 />
            <Column_0032 />
            <Column_0016 />
            <Column_0016 />
            <Column />
            <Column_0001 />
            <Column_0002 />
            <Column_0003 />
            <Column_0051 />
            <Column_0051 />
            <Column_0053 />
            <Column_0051 />
            <Column_0055 />
            <Column_0056 />
            <Column_0016 />
            <Column_0016 />
            <Column_0055 />
            <Column_0016 />
            <Column_0061 />
            <Column_0016 />
            <Column_0014 />
            <Column_0055 />
            <Column_0055 />
            <Column_0055 />
            <Column_0055 />
            <Column_0016 />
            <Column_0069 />
            <Column_0069 />
            <Column_0071 />
            <Column_0072 />
          </Chart>
          <Line>
            <Bg />
            <Cian />
            <Yellow />
          </Line>
        </Graph>
      </WidgetLSizeTimelineChart>
      <NavigationBar>
        <Background />
        <Search>
          <Input />
          <Icon
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/953f85d4-7e0b-4b0d-9fc7-0569d2c218bf"
            alt="icon"
          />
        </Search>
        <Tab />
        <Menu>
          <Label>Statistics</Label>
          <Label_0001>Overview</Label_0001>
          <Label>Dashboard</Label>
          <Label>Analytics</Label>
        </Menu>
        <Profile
          src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/333956f8-5377-4d63-932e-4e82f8d97c77"
          alt="icon"
        />
        <Option
          src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/c25f912b-cc64-4ca7-9183-b28be27d4017"
          alt="icon"
        />
        <Logo>
          <Logo_0001 />
          <Name>ORION</Name>
        </Logo>
      </NavigationBar>
      <Footer>
        <Bg_0001 />
        <OrionDataVisualisation>Orion data visualisation</OrionDataVisualisation>
        <_2019>2019</_2019>
      </Footer>
      <SideIndicators>
        <InformerInfoWithIcon>
          <Icon_0001>
            <Background_0001 />
            <Activity
              src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/02986c35-3c5e-4c79-a194-e7e6fa368f52"
              alt="icon"
            />
          </Icon_0001>
          <Info_0001>
            <Title_0001>Total earning</Title_0001>
            <Amount>
              <Value_0003>540,549</Value_0003>
            </Amount>
          </Info_0001>
        </InformerInfoWithIcon>
        <InformerInfoWithIcon>
          <Icon_0001>
            <Background_0002 />
            <Crown
              src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/42697219-175c-43a7-bd39-7827922e944f"
              alt="icon"
            />
          </Icon_0001>
          <Info_0001>
            <Title_0001>Sales</Title_0001>
            <Amount>
              <Value_0003>1,205,677</Value_0003>
            </Amount>
          </Info_0001>
        </InformerInfoWithIcon>
        <InformerInfoWithIcon>
          <Icon_0001>
            <Background_0003 />
            <Chart_0001
              src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/144c4c0a-0dbb-47c6-a693-14681cac0cd5"
              alt="icon"
            />
          </Icon_0001>
          <Info_0001>
            <Title_0001>Purchase</Title_0001>
            <Amount>
              <Value_0003>48,430,039</Value_0003>
            </Amount>
          </Info_0001>
        </InformerInfoWithIcon>
      </SideIndicators>
      <WidgetMSizeBigCircleChart>
        <Chart_0002>
          <Percent>27%</Percent>
          <Background_0004 />
          <Progress
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/ad00ffba-9101-4489-bde6-afa4b08c8301"
            alt="image from ellipse"
          />
        </Chart_0002>
        <Info_0004>
          <Amount_0003>92,980</Amount_0003>
          <Detail>Active users</Detail>
        </Info_0004>
      </WidgetMSizeBigCircleChart>
      <WidgetMSizeBigCircleChart_0001>
        <Chart_0002>
          <Percent>67%</Percent>
          <Background_0004 />
          <Progress
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/c96c93aa-f3b0-4945-8415-a1693717963c"
            alt="image from ellipse"
          />
        </Chart_0002>
        <Info_0004>
          <Amount_0003>22,652</Amount_0003>
          <Detail>New users</Detail>
        </Info_0004>
      </WidgetMSizeBigCircleChart_0001>
      <HexMap />
      <MapPinPinWithName>
        <Tooltip>
          <Indicator
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/f3d86c23-1831-4ef0-a1a0-f35d310af04c"
            alt="icon"
          />
          <Info_0001>
            <Title_0004>Chicago</Title_0004>
            <Amount_0005>98,320,300</Amount_0005>
          </Info_0001>
        </Tooltip>
        <Arrow xmlns="http://www.w3.org/2000/svg">
          <path fill="white" d="M12.8571 0L23.9917 13.5L1.72253 13.5L12.8571 0Z" />
        </Arrow>
      </MapPinPinWithName>
      <MapPinPinWithName_0001>
        <Tooltip_0001>
          <Indicator
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/f5d9a594-4698-4c32-bf62-dfed04ad4e07"
            alt="icon"
          />
          <Info_0001>
            <Title_0004>Manaus</Title_0004>
            <Amount_0005>12,320,300</Amount_0005>
          </Info_0001>
        </Tooltip_0001>
        <Arrow xmlns="http://www.w3.org/2000/svg">
          <path fill="white" d="M12.8571 0L23.9917 13.5L1.72253 13.5L12.8571 0Z" />
        </Arrow>
      </MapPinPinWithName_0001>
      <MapPinPinWithName_0002>
        <Tooltip_0002>
          <Indicator
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/9699e8f2-0081-41c6-9c47-f104f7052fc9"
            alt="icon"
          />
          <Info_0001>
            <Title_0004>Berlin</Title_0004>
            <Amount_0005>76,541,106</Amount_0005>
          </Info_0001>
        </Tooltip_0002>
        <Arrow xmlns="http://www.w3.org/2000/svg">
          <path fill="white" d="M12.8571 0L23.9917 13.5L1.72253 13.5L12.8571 0Z" />
        </Arrow>
      </MapPinPinWithName_0002>
      <MapPinPinWithName_0003>
        <Tooltip_0003>
          <Indicator
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/a61f7db7-9fd3-4270-86a5-d45460ce6ec2"
            alt="icon"
          />
          <Info_0001>
            <Title_0004>Giza</Title_0004>
            <Amount_0005>10,547,980</Amount_0005>
          </Info_0001>
        </Tooltip_0003>
        <Arrow xmlns="http://www.w3.org/2000/svg">
          <path fill="white" d="M12.8571 0L23.9917 13.5L1.72253 13.5L12.8571 0Z" />
        </Arrow>
      </MapPinPinWithName_0003>
      <MapPinPinWithName_0004>
        <Tooltip>
          <Indicator
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/a6036d66-eb13-4019-8f9d-fa3bf9024a40"
            alt="icon"
          />
          <Info_0001>
            <Title_0004>Shanghai</Title_0004>
            <Amount_0005>239,570,110</Amount_0005>
          </Info_0001>
        </Tooltip>
        <Arrow xmlns="http://www.w3.org/2000/svg">
          <path fill="white" d="M12.8571 0L23.9917 13.5L1.72253 13.5L12.8571 0Z" />
        </Arrow>
      </MapPinPinWithName_0004>
      <MapPinPinWithName_0005>
        <Tooltip_0005>
          <Indicator
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/bf68773a-1eeb-4f60-93f0-4612fb4c8d28"
            alt="icon"
          />
          <Info_0001>
            <Title_0004>Queensland</Title_0004>
            <Amount_0005>6,097,321</Amount_0005>
          </Info_0001>
        </Tooltip_0005>
        <Arrow xmlns="http://www.w3.org/2000/svg">
          <path fill="white" d="M12.8571 0L23.9917 13.5L1.72253 13.5L12.8571 0Z" />
        </Arrow>
      </MapPinPinWithName_0005>
      <Footer>
        <Bg_0001 />
        <Description>Orion data visualisation</Description>
        <_2019>2022</_2019>
      </Footer>
      <Amount_0011>2,431,340</Amount_0011>
      <Title_0010>
        <Name_0001>All users</Name_0001>
        <Detail_0002>
          <Detail_0003>Detail</Detail_0003>
          <Arow
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/6c69251d-3f49-4fee-ad55-dc0b6a722b7f"
            alt="icon"
          />
        </Detail_0002>
      </Title_0010>
    </RootWrapperWorldHexagonMap>
  );
}

const RootWrapperWorldHexagonMap = styled.div`
	min-height: 100vh;
	background-color: rgb(238, 240, 250);
	border-radius: 10px;
	position: relative;
`;

const WidgetLSizeTimelineChart = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 17px;
	box-shadow: 0px 100px 80px  rgba(108, 73, 172, 0.07),0px 42px 33px  rgba(108, 73, 172, 0.05),0px 22px 18px  rgba(108, 73, 172, 0.04),0px 13px 10px  rgba(108, 73, 172, 0.04),0px 7px 5px  rgba(108, 73, 172, 0.03),0px 3px 2px  rgba(108, 73, 172, 0.02);
	border-radius: 10px;
	background-color: white;
	box-sizing: border-box;
	position: absolute;
	left: calc((calc((50% + 0px)) - 900px));
	bottom: 66px;
	width: 1800px;
	height: 86px;
`;

const Info = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	flex: none;
	gap: 10px;
	border-radius: 10px;
	width: 132px;
	background-color: white;
	box-sizing: border-box;
	padding: 0px 32px;
`;

const Value = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 59px;
	box-sizing: border-box;
`;

const Value_0001 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	gap: 2px;
	box-sizing: border-box;
`;

const Title = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 20px;
	text-align: left;
`;

const Value_0002 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 22px;
	font-family: Poppins, sans-serif;
	font-weight: 600;
	line-height: 36px;
	text-align: left;
`;

const Graph = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: center;
	flex: none;
	gap: 2px;
	border-radius: 10px;
	width: 1651px;
	background-color: white;
	box-sizing: border-box;
	padding: 20px 32px;
`;

const Chart = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-end;
	flex: none;
	gap: 2px;
	box-sizing: border-box;
`;

const Column = styled.div`
	width: 20px;
	height: 25px;
	background-color: rgb(219, 223, 241);
`;

const Column_0001 = styled.div`
	width: 20px;
	height: 27px;
	background-color: rgb(219, 223, 241);
`;

const Column_0002 = styled.div`
	width: 20px;
	height: 28px;
	background-color: rgb(219, 223, 241);
`;

const Column_0003 = styled.div`
	width: 20px;
	height: 31px;
	background-color: rgb(219, 223, 241);
`;

const Column_0004 = styled.div`
	width: 21px;
	height: 31px;
	background-color: rgb(219, 223, 241);
`;

const Column_0005 = styled.div`
	width: 21px;
	height: 24px;
	background-color: rgb(219, 223, 241);
`;

const Column_0007 = styled.div`
	width: 20px;
	height: 38px;
	background-color: rgb(219, 223, 241);
`;

const Column_0008 = styled.div`
	width: 20px;
	height: 36px;
	background-color: rgb(219, 223, 241);
`;

const Column_0014 = styled.div`
	width: 20px;
	height: 24px;
	background-color: rgb(219, 223, 241);
`;

const Column_0015 = styled.div`
	width: 20px;
	height: 14px;
	background-color: rgb(219, 223, 241);
`;

const Column_0016 = styled.div`
	width: 20px;
	height: 19px;
	background-color: rgb(219, 223, 241);
`;

const Column_0017 = styled.div`
	width: 20px;
	height: 18px;
	background-color: rgb(219, 223, 241);
`;

const Column_0019 = styled.div`
	width: 20px;
	height: 14px;
	background-color: rgb(255, 112, 139);
`;

const Column_0020 = styled.div`
	width: 20px;
	height: 16px;
	background-color: rgb(255, 112, 139);
`;

const Column_0021 = styled.div`
	width: 20px;
	height: 17px;
	background-color: rgb(255, 112, 139);
`;

const Column_0022 = styled.div`
	width: 20px;
	height: 19px;
	background-color: rgb(255, 112, 139);
`;

const Column_0023 = styled.div`
	width: 20px;
	height: 25px;
	background-color: rgb(255, 112, 139);
`;

const Column_0024 = styled.div`
	width: 20px;
	height: 27px;
	background-color: rgb(255, 112, 139);
`;

const Column_0025 = styled.div`
	width: 20px;
	height: 28px;
	background-color: rgb(255, 112, 139);
`;

const Column_0027 = styled.div`
	width: 21px;
	height: 14px;
	background-color: rgb(255, 112, 139);
`;

const Column_0029 = styled.div`
	width: 21px;
	height: 24px;
	background-color: rgb(255, 112, 139);
`;

const Column_0032 = styled.div`
	width: 20px;
	height: 17px;
	background-color: rgb(219, 223, 241);
`;

const Column_0043 = styled.div`
	width: 20px;
	height: 16px;
	background-color: rgb(219, 223, 241);
`;

const Column_0051 = styled.div`
	width: 21px;
	height: 19px;
	background-color: rgb(219, 223, 241);
`;

const Column_0053 = styled.div`
	width: 21px;
	height: 13px;
	background-color: rgb(219, 223, 241);
`;

const Column_0055 = styled.div`
	width: 20px;
	height: 22px;
	background-color: rgb(219, 223, 241);
`;

const Column_0056 = styled.div`
	width: 20px;
	height: 21px;
	background-color: rgb(219, 223, 241);
`;

const Column_0061 = styled.div`
	width: 20px;
	height: 13px;
	background-color: rgb(219, 223, 241);
`;

const Column_0069 = styled.div`
	width: 20px;
	height: 9px;
	background-color: rgb(219, 223, 241);
`;

const Column_0071 = styled.div`
	width: 20px;
	height: 10px;
	background-color: rgb(219, 223, 241);
`;

const Column_0072 = styled.div`
	width: 20px;
	height: 11px;
	background-color: rgb(219, 223, 241);
`;

const Line = styled.div`
	width: 1593px;
	height: 6px;
	position: relative;
`;

const Bg = styled.div`
	background-color: rgb(134, 118, 255);
	border-radius: 100px;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 0px;
`;

const Cian = styled.div`
	background-color: rgb(255, 112, 139);
	border-radius: 100px;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 869px;
	bottom: 0px;
`;

const Yellow = styled.div`
	background-color: rgb(255, 166, 63);
	border-radius: 100px;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 1353px;
	bottom: 0px;
`;

const NavigationBar = styled.div`
	height: 60px;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
`;

const Background = styled.div`
	background-color: white;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 0px;
`;

const Search = styled.div`
	width: 520px;
	height: 32px;
	position: absolute;
	left: calc((calc((50% + -300px)) - 260px));
	top: calc((calc((50% + 0px)) - 16px));
`;

const Input = styled.div`
	width: 520px;
	height: 32px;
	background-color: rgb(238, 240, 250);
	border-radius: 8px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Icon = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
	position: absolute;
	top: calc((calc((50% + 0px)) - 12px));
	right: 7px;
`;

const Tab = styled.div`
	background-color: rgb(87, 86, 179);
	position: absolute;
	left: 1169px;
	top: 57px;
	right: 645px;
	bottom: 0px;
`;

const Menu = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 84px;
	box-sizing: border-box;
	position: absolute;
	left: calc((calc((50% + 353px)) - 286px));
	top: calc((calc((50% + 0px)) - 12px));
	width: 571px;
	height: 24px;
`;

const Label = styled.span`
	color: rgb(132, 132, 160);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: left;
`;

const Label_0001 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: left;
`;

const Profile = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
	position: absolute;
	top: calc((calc((50% + 0px)) - 12px));
	right: 110px;
`;

const Option = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
	position: absolute;
	top: calc((calc((50% + 0px)) - 12px));
	right: 60px;
`;

const Logo = styled.div`
	width: 112px;
	height: 32px;
	overflow: hidden;
	position: absolute;
	left: 60px;
	top: 14px;
`;

const Logo_0001 = styled.div`
	width: 21px;
	height: 21px;
	border-radius: 21px / 21px;
	position: absolute;
	left: 5px;
	top: calc((calc((50% + -1px)) - 11px));
`;

const Name = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 21px;
	font-family: Archivo, sans-serif;
	font-weight: 400;
	text-align: left;
	position: absolute;
	left: 37px;
	top: calc((calc((50% + 0px)) - 11px));
`;

const Footer = styled.div`
	height: 38px;
	position: absolute;
	left: 0px;
	right: 0px;
	bottom: 0px;
`;

const Bg_0001 = styled.div`
	background-color: white;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 0px;
`;

const OrionDataVisualisation = styled.span`
	color: rgb(90, 90, 137);
	text-overflow: ellipsis;
	font-size: 10px;
	font-family: Roboto, sans-serif;
	font-weight: 700;
	letter-spacing: 2px;
	line-height: 16px;
	text-align: left;
	text-transform: uppercase;
	position: absolute;
	left: 67px;
	top: calc((calc((50% + 0px)) - 8px));
`;

const _2019 = styled.span`
	color: rgb(90, 90, 137);
	text-overflow: ellipsis;
	font-size: 10px;
	font-family: Roboto, sans-serif;
	font-weight: 700;
	letter-spacing: 2px;
	line-height: 16px;
	text-align: right;
	text-transform: uppercase;
	position: absolute;
	top: calc((calc((50% + 0px)) - 8px));
	right: 67px;
`;

const SideIndicators = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 30px;
	box-sizing: border-box;
	position: absolute;
	left: 60px;
	top: 406px;
	width: 218px;
	height: 270px;
`;

const InformerInfoWithIcon = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 26px;
	box-sizing: border-box;
`;

const Icon_0001 = styled.div`
	width: 70px;
	height: 70px;
	position: relative;
`;

const Background_0001 = styled.div`
	width: 70px;
	height: 70px;
	background-color: rgb(134, 118, 255);
	border-radius: 20px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Activity = styled.img`
	width: 32px;
	height: 32px;
	object-fit: cover;
	position: absolute;
	left: 20px;
	top: 20px;
`;

const Info_0001 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	box-sizing: border-box;
`;

const Title_0001 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 32px;
	text-align: left;
`;

const Amount = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 4px;
	box-sizing: border-box;
`;

const Value_0003 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Poppins, sans-serif;
	font-weight: 600;
	line-height: 32px;
	text-align: left;
`;

const Background_0002 = styled.div`
	width: 70px;
	height: 70px;
	background-color: rgb(102, 200, 255);
	border-radius: 20px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Crown = styled.img`
	width: 32px;
	height: 32px;
	object-fit: cover;
	position: absolute;
	left: 20px;
	top: 20px;
`;

const Background_0003 = styled.div`
	width: 70px;
	height: 70px;
	background-color: rgb(255, 144, 102);
	border-radius: 20px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Chart_0001 = styled.img`
	width: 32px;
	height: 32px;
	object-fit: cover;
	position: absolute;
	left: 20px;
	top: 20px;
`;

const WidgetMSizeBigCircleChart = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 18px;
	border-radius: 10px;
	box-sizing: border-box;
	position: absolute;
	left: 60px;
	top: calc((calc((50% + 288px)) - 44px));
	width: 220px;
	height: 88px;
`;

const Chart_0002 = styled.div`
	width: 88px;
	height: 88px;
	position: relative;
`;

const Percent = styled.span`
	color: rgb(23, 23, 37);
	text-overflow: ellipsis;
	font-size: 24px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	text-align: center;
	min-height: 37px;
	position: absolute;
	left: 13px;
	top: calc((calc((50% + 1px)) - 19px));
	right: 13px;
	height: 37px;
`;

const Background_0004 = styled.div`
	width: 88px;
	height: 88px;
	border-radius: 88px / 88px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Progress = styled.img`
	width: 88px;
	height: 88px;
	object-fit: contain;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Info_0004 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	flex: none;
	gap: 1px;
	box-sizing: border-box;
`;

const Amount_0003 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Roboto, sans-serif;
	font-weight: 400;
	line-height: 32px;
	text-align: left;
	width: 70px;
	min-height: 30px;
`;

const Detail = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 24px;
	text-align: left;
	width: 108px;
	min-height: 25px;
`;

const WidgetMSizeBigCircleChart_0001 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 18px;
	border-radius: 10px;
	box-sizing: border-box;
	position: absolute;
	left: 330px;
	top: calc((calc((50% + 288px)) - 44px));
	width: 220px;
	height: 88px;
`;

const HexMap = styled.div`
	width: 1341px;
	height: 756px;
	position: absolute;
	box-shadow: 0px 100px 80px  rgba(108, 73, 172, 0.07),0px 42px 33px  rgba(108, 73, 172, 0.05),0px 22px 18px  rgba(108, 73, 172, 0.04),0px 13px 10px  rgba(108, 73, 172, 0.04),0px 7px 5px  rgba(108, 73, 172, 0.03),0px 3px 2px  rgba(108, 73, 172, 0.02);
	top: calc((calc((50% + -53px)) - 378px));
	right: 137px;
`;

const MapPinPinWithName = styled.div`
	width: 180px;
	height: 72px;
	position: absolute;
	box-shadow: 0px 141px 113px  rgba(41, 52, 149, 0.21),0px 59px 47px  rgba(41, 52, 149, 0.15),0px 31px 25px  rgba(41, 52, 149, 0.13),0px 18px 14px  rgba(41, 52, 149, 0.1),0px 9px 7px  rgba(41, 52, 149, 0.08),0px 4px 3px  rgba(41, 52, 149, 0.06);
	top: calc((calc((50% + -214px)) - 36px));
	right: 1147px;
`;

const Tooltip = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 12px;
	border-radius: 16px;
	background-color: white;
	box-sizing: border-box;
	padding: 6px 10px;
	position: absolute;
	left: 0px;
	top: 0px;
	width: 184px;
	height: 60px;
`;

const Indicator = styled.img`
	width: 40px;
	height: 40px;
	object-fit: cover;
`;

const Title_0004 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: Poppins, sans-serif;
	font-weight: 300;
	line-height: 20px;
	text-align: left;
`;

const Amount_0005 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Poppins, sans-serif;
	font-weight: 600;
	line-height: 28px;
	text-align: left;
`;

const Arrow = styled.svg`
	width: 26px;
	height: 18px;
	position: absolute;
	left: calc((calc((50% + 26px)) - 13px));
	bottom: -18px;
	transform: rotate(-180deg);
	transform-origin: top left;
`;

const MapPinPinWithName_0001 = styled.div`
	width: 180px;
	height: 72px;
	position: absolute;
	box-shadow: 0px 141px 113px  rgba(41, 52, 149, 0.21),0px 59px 47px  rgba(41, 52, 149, 0.15),0px 31px 25px  rgba(41, 52, 149, 0.13),0px 18px 14px  rgba(41, 52, 149, 0.1),0px 9px 7px  rgba(41, 52, 149, 0.08),0px 4px 3px  rgba(41, 52, 149, 0.06);
	top: calc((calc((50% + 33px)) - 36px));
	right: 1024px;
`;

const Tooltip_0001 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 12px;
	border-radius: 16px;
	background-color: white;
	box-sizing: border-box;
	padding: 6px 10px;
	position: absolute;
	left: 0px;
	top: 0px;
	width: 177px;
	height: 60px;
`;

const MapPinPinWithName_0002 = styled.div`
	width: 180px;
	height: 72px;
	position: absolute;
	box-shadow: 0px 141px 113px  rgba(41, 52, 149, 0.21),0px 59px 47px  rgba(41, 52, 149, 0.15),0px 31px 25px  rgba(41, 52, 149, 0.13),0px 18px 14px  rgba(41, 52, 149, 0.1),0px 9px 7px  rgba(41, 52, 149, 0.08),0px 4px 3px  rgba(41, 52, 149, 0.06);
	top: calc((calc((50% + -296px)) - 36px));
	right: 692px;
`;

const Tooltip_0002 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 12px;
	border-radius: 16px;
	background-color: white;
	box-sizing: border-box;
	padding: 6px 10px;
	position: absolute;
	left: 0px;
	top: 0px;
	width: 174px;
	height: 60px;
`;

const MapPinPinWithName_0003 = styled.div`
	width: 180px;
	height: 72px;
	position: absolute;
	box-shadow: 0px 141px 113px  rgba(41, 52, 149, 0.21),0px 59px 47px  rgba(41, 52, 149, 0.15),0px 31px 25px  rgba(41, 52, 149, 0.13),0px 18px 14px  rgba(41, 52, 149, 0.1),0px 9px 7px  rgba(41, 52, 149, 0.08),0px 4px 3px  rgba(41, 52, 149, 0.06);
	top: calc((calc((50% + -80px)) - 36px));
	right: 605px;
`;

const Tooltip_0003 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 12px;
	border-radius: 16px;
	background-color: white;
	box-sizing: border-box;
	padding: 6px 10px;
	position: absolute;
	left: 0px;
	top: 0px;
	width: 180px;
	height: 60px;
`;

const MapPinPinWithName_0004 = styled.div`
	width: 180px;
	height: 72px;
	position: absolute;
	box-shadow: 0px 141px 113px  rgba(41, 52, 149, 0.21),0px 59px 47px  rgba(41, 52, 149, 0.15),0px 31px 25px  rgba(41, 52, 149, 0.13),0px 18px 14px  rgba(41, 52, 149, 0.1),0px 9px 7px  rgba(41, 52, 149, 0.08),0px 4px 3px  rgba(41, 52, 149, 0.06);
	top: calc((calc((50% + -148px)) - 36px));
	right: 224px;
`;

const MapPinPinWithName_0005 = styled.div`
	width: 180px;
	height: 72px;
	position: absolute;
	box-shadow: 0px 141px 113px  rgba(41, 52, 149, 0.21),0px 59px 47px  rgba(41, 52, 149, 0.15),0px 31px 25px  rgba(41, 52, 149, 0.13),0px 18px 14px  rgba(41, 52, 149, 0.1),0px 9px 7px  rgba(41, 52, 149, 0.08),0px 4px 3px  rgba(41, 52, 149, 0.06);
	top: calc((calc((50% + 152px)) - 36px));
	right: 113px;
`;

const Tooltip_0005 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	gap: 12px;
	border-radius: 16px;
	background-color: white;
	box-sizing: border-box;
	padding: 6px 10px;
	position: absolute;
	left: 0px;
	top: 0px;
	width: 173px;
	height: 60px;
`;

const Description = styled.span`
	color: rgb(90, 90, 137);
	text-overflow: ellipsis;
	font-size: 10px;
	font-family: Roboto, sans-serif;
	font-weight: 700;
	letter-spacing: 2px;
	line-height: 16px;
	text-align: left;
	text-transform: uppercase;
	position: absolute;
	left: 67px;
	top: calc((calc((50% + 0px)) - 8px));
`;

const Amount_0011 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 72px;
	font-family: Poppins, sans-serif;
	font-weight: 500;
	letter-spacing: -2px;
	line-height: 118px;
	text-align: left;
	position: absolute;
	left: 60px;
	top: 201px;
`;

const Title_0010 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: flex-end;
	gap: 24px;
	box-sizing: border-box;
	position: absolute;
	left: 60px;
	top: 183px;
	width: 177px;
	height: 32px;
`;

const Name_0001 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: Poppins, sans-serif;
	font-weight: 600;
	line-height: 32px;
	text-align: left;
`;

const Detail_0002 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: row;
	align-items: center;
	flex: none;
	gap: 1px;
	box-sizing: border-box;
`;

const Detail_0003 = styled.span`
	color: rgb(56, 56, 116);
	text-overflow: ellipsis;
	font-size: 10px;
	font-family: Roboto, sans-serif;
	font-weight: 700;
	letter-spacing: 2px;
	line-height: 16px;
	text-align: left;
	text-transform: uppercase;
`;

const Arow = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
`;
